tools = [
    {
        "type": "function",
        "function": {
            "name": "parse-recruiters",
            "description": "You are a parser that takes in recruiter messages and converts them in to a JSON object",
            "parameters": {
                "type": "object",
                "properties": {
                    "currency_format": {
                        "type": "string",
                        "enum": [
                                    "AFN", 
                                    "ALL", 
                                    "DZD", 
                                    "AOA", 
                                    "ARS", 
                                    "AMD", 
                                    "AUD", 
                                    "AZN", 
                                    "BSD", 
                                    "BHD", 
                                    "BDT", 
                                    "BBD", 
                                    "BYN", 
                                    "BZD", 
                                    "BMD", 
                                    "BTN", 
                                    "BOB", 
                                    "BAM",  
                                    "BWP", 
                                    "BRL", 
                                    "GBP",  
                                    "BND", 
                                    "BGN", 
                                    "BIF", 
                                    "KHR", 
                                    "CAD", 
                                    "CVE",  
                                    "KYD",  
                                    "XAF",   
                                    "CLP", 
                                    "CNY", 
                                    "COP", 
                                    "KMF", 
                                    "CDF", 
                                    "CRC",  
                                    "HRK", 
                                    "CUP", 
                                    "CZK", 
                                    "DKK", 
                                    "DJF", 
                                    "DOP", 
                                    "XCD",  
                                    "EGP", 
                                    "ERN", 
                                    "SZL", 
                                    "ETB", 
                                    "EUR", 
                                    "GMD", 
                                    "GEL", 
                                    "GHS", 
                                    "GTQ", 
                                    "GNF", 
                                    "GYD", 
                                    "HTG", 
                                    "HNL", 
                                    "HKD",  
                                    "HUF", 
                                    "ISK", 
                                    "INR", 
                                    "IDR", 
                                    "IRR", 
                                    "IQD", 
                                    "ILS",  
                                    "JMD", 
                                    "JPY", 
                                    "JOD", 
                                    "KZT", 
                                    "KES", 
                                    "KWD", 
                                    "KGS", 
                                    "LAK", 
                                    "LBP", 
                                    "LSL", 
                                    "LRD", 
                                    "LYD", 
                                    "MOP", 
                                    "MKD", 
                                    "MGA", 
                                    "MWK", 
                                    "MYR", 
                                    "MVR", 
                                    "MRU", 
                                    "MUR", 
                                    "MXN", 
                                    "MDL", 
                                    "MNT", 
                                    "MAD", 
                                    "MZN", 
                                    "MMK", 
                                    "NAD", 
                                    "NPR", 
                                    "ANG",  
                                    "TWD",  
                                    "NZD",  
                                    "NIO", 
                                    "NGN", 
                                    "KPW",  
                                    "NOK", 
                                    "OMR", 
                                    "PKR", 
                                    "PAB", 
                                    "PGK",   
                                    "PYG", 
                                    "PEN",  
                                    "PHP", 
                                    "PLN", 
                                    "QAR", 
                                    "RON", 
                                    "RUB", 
                                    "RWF", 
                                    "SHP",  
                                    "WST", 
                                    "STN",  
                                    "SAR", 
                                    "RSD", 
                                    "SCR", 
                                    "SLL",  
                                    "SGD", 
                                    "SBD",  
                                    "SOS", 
                                    "ZAR",  
                                    "KRW",  
                                    "SSP",  
                                    "LKR",  
                                    "SDG", 
                                    "SRD", 
                                    "SEK", 
                                    "CHF", 
                                    "SYP", 
                                    "TJS", 
                                    "TZS", 
                                    "THB", 
                                    "TOP", 
                                    "TTD",  
                                    "TND", 
                                    "TRY", 
                                    "TMT", 
                                    "UGX", 
                                    "UAH", 
                                    "AED", 
                                    "USD",  
                                    "UYU", 
                                    "UZS", 
                                    "VUV", 
                                    "VES", 
                                    "VND", 
                                    "XOF",   
                                    "YER", 
                                    "ZMW", 
                                    "ZWL"  
                                    ],
                        "description": "Monetary unit of salary. If no valid currency is found, it can be determined based on the input's language or country reference"
                    },
                    "unit_of_time_for_holidays": {
                      "type": "number",
                      "enum": ["day", "month", "year"],
                      "description": "The holidays during the year must be expressed in time units appropriate to their duration"  
                    },
                    "unit_of_time_for_position_experience": {
                        "type": "string",
                        "enum": ["month", "year"],
                        "description": "Position experience must be expressed in time units appropriate to the duration of the experience",
                    },
                    "is_remote": {
                        "type": "boolean",
                        "description": "whether or not the opportunity is remote",
                    },
                    "salary_min": {
                        "type": "number",
                        "description": "The minimum salary",
                    },
                    "salary_max": {
                        "type": "number",
                        "description": "The maximum salary",
                    },
                    "contract": {
                        "type": "boolean",
                        "description": "Whether or not the position is a contract/freelance position, or a full-time role",
                    },
                    "role_name": {
                        "type": "string",
                        "description": "The name of the role, if possible",
                    },
                    "benefits": {
                        "type": "string",
                        "description": "Any miscellaneous benefits",
                    },
                    "notes": {
                        "type": "string",
                        "description": "Any extra information you see that may be of note",
                    },
                    "experience": {
                        "type": "number",
                        "description": "If added, the amount of experience required in years",
                    },
                    "recruiter": {
                        "type": "string",
                        "description": "The name of the recruiter",
                    },
                    "next_step": {
                        "type": "string",
                        "description": "The suggested next step in the recruitment process, usually a call or interview"
                    },
                    "holidays": {
                        "type": "number",
                        "description": "The holiday during the year"
                    },
                    "city": {
                        "type": "string",
                        "description": "The city"
                    },
                    "country": {
                        "type": "string",
                        "description": "The country."
                    },
                     "title": {
                        "type": "string",
                        "description": "Create a title for the prompt."
                    }
                },
                "required": ["is_remote", "salary_min", "salary_max", "contract", "role_name", "benefits", "notes", "experience",
                             "recruiter", "next_step", "holiday", "city", "country", "title",
                             "unit_of_time_for_position_experience", "unit_of_time_for_holidays", "currency_format"],
            },
        }
    }
]
